export const artists = [
    { artist: "Akon", genres: ["R&B", "Trance"] },
    { artist: "Baba Harare", genres: ["Dancehall", "Zim Dancehall"] },
    { artist: "Shinsoman", genres: ["Dancehall", "Zim Dancehall"] },
    { artist: "Master H", genres: ["Dancehall", "Zim Dancehall"] },
    { artist: "Silent Killer", genres: ["Dancehall", "Zim Dancehall"] },
    { artist: "Nutty O", genres: ["Dancehall", "Zim Dancehall"] },
    { artist: "Tocky Vibes", genres: ["Dancehall", "Zim Dancehall"] },
    { artist: "Jah Signal", genres: ["Dancehall", "Zim Dancehall"] },
    { artist: "Enzo Ishall", genres: ["Dancehall", "Zim Dancehall"] },
    { artist: "Soul Jah Love", genres: ["Dancehall", "Zim Dancehall"] },
    { artist: "Poptain", genres: ["Dancehall", "Zim Dancehall"] },
    { artist: "Jah Prayzah", genres: ["Dancehall", "Zim Dancehall"] },
    { artist: "Holy Ten", genres: ["Dancehall", "Zim Dancehall"] },
    { artist: "Ti Gonzi", genres: ["Dancehall", "Zim Dancehall"] },
    { artist: "Freeman & Nox", genres: ["Dancehall", "Zim Dancehall"] },
    { artist: "Bazooker", genres: ["Dancehall", "Zim Dancehall"] },
    { artist: "Ras Caleb", genres: ["Dancehall", "Zim Dancehall"] },
    { artist: "Kinnah", genres: ["Dancehall", "Zim Dancehall"] },
    { artist: "Chillspot Family", genres: ["Dancehall", "Zim Dancehall"] },
    { artist: "Silent Killer", genres: ["Dancehall", "Zim Dancehall"] },

    // 🇯🇲 Reggae Legends
    { artist: "Bob Marley & The Wailers", genres: ["Reggae"] },
    { artist: "Peter Tosh", genres: ["Reggae"] },
    { artist: "Burning Spear", genres: ["Reggae"] },
    { artist: "Jimmy Cliff", genres: ["Reggae"] },
    { artist: "Toots and the Maytals", genres: ["Reggae"] },
    { artist: "Gregory Isaacs", genres: ["Reggae"] },
    { artist: "Dennis Brown", genres: ["Reggae"] },
    { artist: "Steel Pulse", genres: ["Reggae"] },
    { artist: "Maxi Priest", genres: ["Reggae"] },
    { artist: "Jacob Miller", genres: ["Reggae"] },

    // 🇯🇲 Dancehall Legends (Jamaica)
    { artist: "Vybz Kartel", genres: ["Dancehall"] },
    { artist: "Beenie Man", genres: ["Dancehall"] },
    { artist: "Bounty Killer", genres: ["Dancehall"] },
    { artist: "Sean Paul", genres: ["Dancehall"] },
    { artist: "Shaggy", genres: ["Dancehall"] },
    { artist: "Popcaan", genres: ["Dancehall"] },
    { artist: "Spice", genres: ["Dancehall"] },
    { artist: "Mavado", genres: ["Dancehall"] },
    { artist: "Alkaline", genres: ["Dancehall"] },
    { artist: "Busy Signal", genres: ["Dancehall"] },
    { artist: "Tarrus Riley", genres: ["Dancehall"] },
    { artist: "Konshens", genres: ["Dancehall"] },
    { artist: "Elephant Man", genres: ["Dancehall"] },
    { artist: "Chronic Law", genres: ["Dancehall"] },
    { artist: "Jahmiel", genres: ["Dancehall"] },

    // 🎷 Soul Legends & Contemporary Soul
    { artist: "Aretha Franklin", genres: ["Soul"] },
    { artist: "Otis Redding", genres: ["Soul"] },
    { artist: "Al Green", genres: ["Soul"] },
    { artist: "Etta James", genres: ["Soul"] },
    { artist: "Sam Cooke", genres: ["Soul"] },
    { artist: "James Brown", genres: ["Soul"] },
    { artist: "Marvin Gaye", genres: ["Soul"] },
    { artist: "Stevie Wonder", genres: ["Soul"] },
    { artist: "Bill Withers", genres: ["Soul"] },
    { artist: "Ray Charles", genres: ["Soul"] },
    { artist: "Anita Baker", genres: ["Soul"] },
    { artist: "Sade", genres: ["Soul"] },
    { artist: "Jill Scott", genres: ["Soul"] },
    { artist: "Erykah Badu", genres: ["Soul"] },
    { artist: "Lauryn Hill", genres: ["Soul"] },
    { artist: "Alicia Keys", genres: ["Soul"] },
    { artist: "John Legend", genres: ["Soul"] },
    { artist: "Amy Winehouse", genres: ["Soul"] },
    { artist: "Maxwell", genres: ["Soul"] },
    { artist: "D'Angelo", genres: ["Soul"] },
    { artist: "Musiq Soulchild", genres: ["Soul"] },

    { artist: "Miles Davis", genres: ["Jazz"] },
    { artist: "John Coltrane", genres: ["Jazz"] },
    { artist: "Herbie Hancock", genres: ["Jazz"] },
    { artist: "Louis Armstrong", genres: ["Jazz"] },
    { artist: "Duke Ellington", genres: ["Jazz"] },
    { artist: "Ella Fitzgerald", genres: ["Jazz"] },
    { artist: "Billie Holiday", genres: ["Jazz"] },
    { artist: "Nina Simone", genres: ["Jazz"] },
    { artist: "Charlie Parker", genres: ["Jazz"] },
    { artist: "Thelonious Monk", genres: ["Jazz"] },


    { artist: "Kirk Franklin", genres: ["Gospel"] },
    { artist: "Donnie McClurkin", genres: ["Gospel"] },
    { artist: "CeCe Winans", genres: ["Gospel"] },
    { artist: "Tasha Cobbs Leonard", genres: ["Gospel"] },
    { artist: "William McDowell", genres: ["Gospel"] },
    { artist: "Benjamin Dube", genres: ["Gospel"] },
    { artist: "Rebecca Malope", genres: ["Gospel"] },
    { artist: "Joyous Celebration", genres: ["Gospel"] },
    { artist: "Ntokozo Mbambo", genres: ["Gospel"] },
    { artist: "Dr Tumi", genres: ["Gospel"] },


    { artist: "Queen", genres: ["Rock"] },
    { artist: "The Rolling Stones", genres: ["Rock"] },
    { artist: "AC/DC", genres: ["Rock"] },
    { artist: "Nirvana", genres: ["Rock"] },
    { artist: "Linkin Park", genres: ["Rock"] },
    { artist: "Foo Fighters", genres: ["Rock"] },
    { artist: "Red Hot Chili Peppers", genres: ["Rock"] },
    { artist: "Metallica", genres: ["Rock"] },
    { artist: "Coldplay", genres: ["Rock"] },
    { artist: "U2", genres: ["Rock"] },


    { artist: "Fela Kuti", genres: ["Afrobeat"] },
    { artist: "Burna Boy", genres: ["Afrobeat"] },
    { artist: "Wizkid", genres: ["Afrobeat"] },
    { artist: "Davido", genres: ["Afrobeat"] },
    { artist: "Tiwa Savage", genres: ["Afrobeat"] },
    { artist: "Rema", genres: ["Afrobeat"] },
    { artist: "Olamide", genres: ["Afrobeat"] },
    { artist: "Mr Eazi", genres: ["Afrobeat"] },
    { artist: "Yemi Alade", genres: ["Afrobeat"] },
    { artist: "Tekno", genres: ["Afrobeat"] },

    { artist: "Alick Macheso", genres: ["Sungura"] },
    { artist: "Tongai Moyo", genres: ["Sungura"] },
    { artist: "Leonard Dembo", genres: ["Sungura"] },
    { artist: "Nicholas Zakaria", genres: ["Sungura"] },
    { artist: "Simon Chimbetu", genres: ["Sungura"] },
    { artist: "John Chibadura", genres: ["Sungura"] },
    { artist: "Mark Ngwazi", genres: ["Sungura"] },
    { artist: "Josphat Somanje", genres: ["Sungura"] },
    { artist: "Suluman Chimbetu", genres: ["Sungura"] },
    { artist: "Somandla Ndebele", genres: ["Sungura"] }
]